### ISSUE TITLE
model of SCAR and SFCN

### ISSUE THREAD

**Issue by CaeTism** [gjy3035/NWPU-Crowd-Sample-Code-for-Localization#2]
Thanks to your amazing work!
Notice that the weights of SCAR-latest.pth and a SFCN+all_ep..pth are also released, that I'm looking forward to test them on my datasets, but I could not find the related scripts in './models/', appreciate that you could release them.

**Comment by gjy3035** [comment]
This repo is a localization code. Please visit: https://github.com/gjy3035/NWPU-Crowd-Sample-Code

**Comment by CaeTism** [comment]
> This repo is a localization code. Please visit: https://github.com/gjy3035/NWPU-Crowd-Sample-Code

Well I see, thanks!
